[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
verbosity = 3
sender = "0x0165C55EF814dEFdd658532A48Bd17B2c8356322"
tx_origin = "0x0165C55EF814dEFdd658532A48Bd17B2c8356322"
auto_detect_remappings = false
gas_reports = ["OethARM", "Proxy", "LidoARM", "OriginARM"]
fs_permissions = [{ access = "read-write", path = "./build" }]
extra_output_files = ["metadata"]
ignored_warnings_from = ["src/contracts/Proxy.sol"]
optimizer = true
optimizer_runs = 200
ffi = true

# About remappings: 
# - @pendle-sy use a different version of oz contracts than the one used in the rest of the project.
# - dependencies remappings (like "dependencies/@pendle-sy"), need to stay amongs first remappings.
remappings = [
  # Manage dependencies remappings inside dependencies folder (has to be first)
  "dependencies/@pendle-sy-1.0.0-1.0.0/:@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-4.9.3-4.9.3/contracts/",
  # Manage root folders remappings
  "contracts/=./src/contracts",
  "script/=./script",
  "test/=./test",
  "utils/=./src/contracts/utils",
  # Manage dependencies remappings
  "@solmate/=dependencies/solmate-6.7.0/src/",
  "forge-std/=dependencies/forge-std-1.9.7/src/",
  "@pendle-sy/=dependencies/@pendle-sy-1.0.0-1.0.0/contracts/",
  "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.0.2-5.0.2/contracts/",
  "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.0.2-5.0.2/contracts/",
]

[fuzz]
runs = 1_000

[invariant]
runs = 256
depth = 500
shrink_run_limit = 5_000
show_metrics = true
fail_on_revert = false

[dependencies]
solmate = "6.7.0"
forge-std = "1.9.7"
"@pendle-sy-1.0.0" = { version = "1.0.0", git = "git@github.com:pendle-finance/Pendle-SY-Public.git", rev = "3256e7728d1656a8e16e2e70aa885f69fc66088d" }
"@openzeppelin-contracts-4.9.3" = { version = "4.9.3", git = "git@github.com:OpenZeppelin/openzeppelin-contracts.git", rev = "fd81a96f01cc42ef1c9a5399364968d0e07e9e90" }
"@openzeppelin-contracts-5.0.2" = { version = "5.0.2", git = "git@github.com:OpenZeppelin/openzeppelin-contracts.git", rev = "dbb6104ce834628e473d2173bbc9d47f81a9eec3" }
"@openzeppelin-contracts-upgradeable-4.9.3" = { version = "4.9.3", git = "git@github.com:OpenZeppelin/openzeppelin-contracts-upgradeable.git", rev = "3d4c0d5741b131c231e558d7a6213392ab3672a5" }
"@openzeppelin-contracts-upgradeable-5.0.2" = { version = "5.0.2", git = "git@github.com:OpenZeppelin/openzeppelin-contracts-upgradeable.git", rev = "723f8cab09cdae1aca9ec9cc1cfa040c2d4b06c1" }

[soldeer]
recursive_deps = false
remappings_version = false
remappings_generate = false
remappings_regenerate = false
remappings_prefix = "@"
remappings_location = "config"

[rpc_endpoints]
mainnet = "${PROVIDER_URL}"
sonic = "${SONIC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
