[profile.default]
src = "src/contracts"
out = "out"
libs = ["dependencies"]
verbosity = 3
sender = "0x0165C55EF814dEFdd658532A48Bd17B2c8356322"
tx_origin = "0x0165C55EF814dEFdd658532A48Bd17B2c8356322"
auto_detect_remappings = false
gas_reports = ["OEthARM", "Proxy"]
fs_permissions = [{ access = "read-write", path = "./build" }]
extra_output_files = ["metadata"]
remappings = [
  "contracts/=./src/contracts",
  "script/=./script",
  "test/=./test",
  "utils/=./src/contracts/utils",
  "forge-std/=dependencies/forge-std-1.9.2/src/",
  "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.0.2/",
  "@openzeppelin/contracts-upgradeable/=dependencies/@openzeppelin-contracts-upgradeable-5.0.2/",
  "@solmate/=dependencies/solmate-6.7.0/src/",
]

[fuzz]
runs = 1_000

[dependencies]
"@openzeppelin-contracts" = "5.0.2"
"@openzeppelin-contracts-upgradeable" = "5.0.2"
forge-std = { version = "1.9.2", git = "https://github.com/foundry-rs/forge-std.git", rev = "5a802d7c10abb4bbfb3e7214c75052ef9e6a06f8" }
solmate = "6.7.0"

[soldeer]
recursive_deps = false
remappings_version = false
remappings_generate = false
remappings_regenerate = false
remappings_prefix = "@"
remappings_location = "config"

[rpc_endpoints]
mainnet = "${PROVIDER_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://etherscan.io/", chain = "mainnet" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
