@startuml

!$originColor = DeepSkyBlue
' !$originColor = WhiteSmoke
!$newColor = LightGreen
!$changedColor = Orange
!$thirdPartyColor = WhiteSmoke

legend
blue - Origin
green - new
orange - changed
white - 3rd Party
end legend

title "Ether.fi (eETH)\nAutomated Redemption Manager (ARM)\nContract Dependencies"


object "ZapperARM" as zap <<Origin>> #$originColor {
}

object "EtherFiARM" as arm <<Origin>><<Proxy>> #$changedColor {
    shares: ARM-eETH-WETH
    liquidity asset: WETH
    base assets: eETH, weETH
}

object "EtherFiAssetAdapter" as eethAdapter <<Origin>> #$newColor {
    base asset: eETH
    pegged: true
}

object "WeETHAssetAdapter" as weethAdapter <<Origin>> #$newColor {
    base asset: weETH
    wrapped asset: eETH
}

object "weETH" as weeth <<EtherFi>> #$thirdPartyColor {
    asset: eETH
}

object "CapManager" as capMan <<Origin>><<Proxy>> #$originColor {
}

object "Redemption\nManager" as rm <<EtherFi>><<Proxy>> #$thirdPartyColor {
}

object "Withdrawal\nQueue" as wq <<EtherFi>><<Proxy>> #$thirdPartyColor {
}

object "Morpho Market" as morphoMarket <<Origin>><<Proxy>> #$originColor {
    asset: WETH
}

object "Yearn WETH ARM Vault" as morpho <<Morpho>> #$thirdPartyColor {
    asset: WETH
}

zap ..> arm
arm <.> capMan
arm ..> eethAdapter
arm ..> weethAdapter
eethAdapter ...> rm
eethAdapter ...> wq
weethAdapter ..> weeth
weethAdapter ...> rm
weethAdapter ...> wq
arm ..> morphoMarket
morphoMarket ..> morpho

@enduml
