@startuml

!theme blueprint

title "Leveraged ARM"

actor "User" as user
participant "Leveraged ARM" as larm <<Origin>>
' participant "Flash Loan" as fl <<Balancer>>
participant "ARM" as arm <<Origin>>
participant "ARM token\nLending Market" as alm <<Aave>>
' participant "ARM LP/WETH\nPool" as curve <<Curve>>
' participant "WETH\nLending Market" as mla <<Morpho>>
' participant "Withdrawal\nQueue" as lwq <<Lido>>

note over arm
1.061763 ARM LP/WETH
end note

note over alm
Max TVL 93%
Liquidation Threshold 95%
end note

' group Deposit to 10x Leveraged ARM
' user -> larm: Deposit 10 WETH
' activate larm
' fl -> larm: Flash loan 90 WETH
' larm -> arm: Deposit 100 WETH
' activate arm
' arm -> larm: 94.1 ARM tokens
' deactivate arm
' larm -> alm: Supply 94.1 ARM tokens as collateral
' alm -> larm: Borrow 90 WETH
' larm -> fl : Repay 90 WETH flash loan
' return Leveraged ARM tokens
' end group


' group Deleverage to 5x Leverage ARM using ARM LP DEX

' fl -> larm: Flash loan 45 WETH
' activate larm
' larm -> alm: Repay the borrowed 45 WETH
' ' alm -> larm: Withdraw collateral of 47.05 ARM tokens

' ' larm -> curve: Swap 47.05 ARM tokens
' ' activate curve
' ' note right: 10 bps slippage
' ' return 49.95 WETH

' ' larm -> fl : Repay 45 WETH flash loan

' ' larm -> arm: Deposit 9.95 WETH to ARM
' ' activate arm
' ' arm -> larm: 9.371 ARM tokens
' ' deactivate arm
' deactivate larm


' end group

' group Withdraw all using ARM LP DEX
' fl -> larm: Flash loan 90 WETH
' activate larm
' larm -> alm: Repay the borrowed 90 WETH
' alm -> larm: Withdraw collateral of 94.1 ARM tokens

' larm -> curve: Swap 94.1 ARM tokens
' activate curve
' note right: 10 bps slippage
' return 99.9 WETH

' larm -> fl : Repay 90 WETH flash loan

' larm -> user: Send 9.9 WETH
' deactivate larm
' end group


group Withdraw using withdrawal request as collateral
alm -> arm : Redeem 94.1 ARM tokens
activate arm
note right: Collateral swapped\nfrom ARM LP tokens\nto ARM withdrawal request
arm -> alm: withdrawal request\nfor 100 WETH
deactivate arm

... 10 minutes to many days ...

alm -> arm : claim withdrawal request
activate arm
arm -> alm: 100 WETH
note right
90 WETH to repay loan
10 WETH as collateral
end note
deactivate arm

alm -> larm: 10 WETH
larm -> user : 10 WETH
end group


@enduml