@startuml

!$originColor = DeepSkyBlue
' !$originColor = WhiteSmoke
!$newColor = LightGreen
!$changedColor = Orange
!$thirdPartyColor = WhiteSmoke

legend
blue - Origin
green - new
orange - changed
white - 3rd Party
end legend

title "Lido (stETH)\nAutomated Redemption Manager (ARM)\nContract Dependencies"


object "ZapperLidoARM" as zap <<Origin>> #$originColor {
}

object "LidoARM" as arm <<Origin>><<Proxy>> #$changedColor {
    shares: ARM-stETH-WETH
    liquidity asset: WETH
    base assets: stETH, wstETH
}

object "StETHAssetAdapter" as stethAdapter <<Origin>> #$newColor {
    base asset: stETH
    pegged: true
}

object "WstETHAssetAdapter" as wstethAdapter <<Origin>> #$newColor {
    base asset: wstETH
    wrapped asset: stETH
}

object "wstETH" as wsteth <<Lido>> #$thirdPartyColor {
    asset: stETH
}

object "CapManager" as capMan <<Origin>><<Proxy>> #$originColor {
}

object "WithdrawalQueueERC721" as lidoQ <<Lido>><<Proxy>> #$thirdPartyColor {
    assets: stETH, WETH
}

object "Morpho Market" as morphoMarket <<Origin>><<Proxy>> #$originColor {
    asset: WETH
}

object "Yearn WETH ARM Vault" as morpho <<Morpho>> #$thirdPartyColor {
    asset: WETH
}

zap <..> arm
arm <.> capMan
arm ..> stethAdapter
arm ..> wstethAdapter
stethAdapter ..> lidoQ
wstethAdapter ..> wsteth
wstethAdapter ..> lidoQ
arm ..> morphoMarket
morphoMarket ..> morpho

@enduml
