@startuml

!$originColor = DeepSkyBlue
' !$originColor = WhiteSmoke
!$newColor = LightGreen
!$changedColor = Orange
!$thirdPartyColor = WhiteSmoke

legend
blue - Origin
green - new
orange - changed
white - 3rd Party
end legend

title "Origin Ether (OETH)\nAutomated Redemption Manager (ARM)\nContract Dependencies"


object "ZapperARM" as zap <<Origin>> #$originColor {
}

object "OriginARM" as arm <<Origin>><<Proxy>> #$changedColor {
    shares: ARM-oETH-WETH
    liquidity asset: WETH
    base assets: OETH, wOETH
}

object "OriginAssetAdapter" as oethAdapter <<Origin>> #$newColor {
    base asset: OETH
    pegged: true
}

object "WrappedOriginAssetAdapter" as woethAdapter <<Origin>> #$newColor {
    base asset: wOETH
    wrapped asset: OETH
}

object "wOETH" as woeth <<Origin>><<ERC4626>> #$thirdPartyColor {
    asset: OETH
}

object "OETHVault" as oethVault <<Origin>><<Proxy>> #$thirdPartyColor {
    assets: oETH, WETH
}

object "Morpho Market" as morphoMarket <<Origin>><<Proxy>> #$originColor {
    asset: WETH
}

object "Yearn WETH ARM Vault" as morpho <<Morpho>> #$thirdPartyColor {
    asset: WETH
}

zap ..> arm
arm ..> oethAdapter
arm ..> woethAdapter
oethAdapter ..> oethVault
woethAdapter ..> woeth
woethAdapter ..> oethVault
arm ..> morphoMarket
morphoMarket ..> morpho

@enduml
