@startuml

!$originColor = DeepSkyBlue
' !$originColor = WhiteSmoke
!$newColor = LightGreen
!$changedColor = Orange
!$thirdPartyColor = WhiteSmoke

legend
blue - Origin
' green - new
' orange - changed
white - 3rd Party
end legend

title "Sonic Automated Redemption Manager (ARM) Contract Dependencies"


' object "Zapper" as zap #$originColor {
' }

' object "Origin ARM" as originArm <<Proxy>> #$originColor {
' }

' object "Beets ARM" as beetsArm <<Proxy>> #$originColor {
' }

' object "Angles ARM" as anglesArm <<Proxy>> #$originColor {
' }

' ' object "CapManager" as capMan <<Proxy>> #$originColor {
' ' }
' object "Origin\nCapManager" as osCapMan <<Proxy>> #$originColor {
' }
' object "Beets\nCapManager" as stCapMan <<Proxy>> #$originColor {
' }
' object "Angles\nCapManager" as anCapMan <<Proxy>> #$originColor {
' }


object "ARM" as arm <<Proxy>> #$originColor {
}
object "Strategy" as strat <<Proxy>> #$originColor {
}

object "Lending\nMarket" as lend #$thirdPartyColor {
}
object "Lending\nMarket\nGauge" as gauge #$thirdPartyColor {
}
object "Liquid\nStaking\nToken" as lst #$thirdPartyColor {
}

' object "OS\nVault" as os <<Proxy>> #$originColor {
' }

' object "Beets\nVault" as beets #$thirdPartyColor {
' }

' object "Angles\nVault" as angles #$thirdPartyColor {
' }

arm .> strat : ERC-4626
strat .> lend : ERC-4626
strat ..> gauge
arm ..> lst

' zap ..> originArm
' zap ..> beetsArm
' zap ..> anglesArm

' ' originArm <..> capMan
' ' beetsArm <..> capMan
' ' anglesArm <..> capMan
' originArm <..> osCapMan
' beetsArm <..> stCapMan
' anglesArm <..> anCapMan

' originArm ..> lend
' beetsArm ..> lend
' anglesArm ..> lend

' originArm ...> os
' beetsArm ...> beets
' anglesArm ...> angles



@enduml