@startuml

!$originColor = DeepSkyBlue
' !$originColor = WhiteSmoke
!$newColor = LightGreen
!$changedColor = Orange
!$thirdPartyColor = WhiteSmoke

legend
blue - Origin
' green - new
' orange - changed
white - 3rd Party
end legend

title "Sonic Automated Redemption Manager (ARM) Contract Dependencies"


object "Sonic Zapper" as zap #$originColor {
    asset: S
}

object "Origin ARM" as originArm <<Proxy>> #$originColor {
    assets: OS, wS
}

' object "Beets ARM" as beetsArm <<Proxy>> #$originColor {
' }

' object "Angles ARM" as anglesArm <<Proxy>> #$originColor {
' }

' object "CapManager" as capMan <<Proxy>> #$originColor {
' }
object "Origin\nCapManager" as osCapMan <<Proxy>> #$originColor {
}
' object "Beets\nCapManager" as stCapMan <<Proxy>> #$originColor {
' }
' object "Angles\nCapManager" as anCapMan <<Proxy>> #$originColor {
' }


' object "ARM" as arm <<Proxy>> #$originColor {
' }
' object "Strategy" as strat <<Proxy>> #$originColor {
' }

object "Silo\nStrategy" as siloStrategy #$originColor {
    asset: wS
}

object "Varlamore\nVault" as siloVault <<Silo>> #$thirdPartyColor {
    asset: wS
}
object "Varlamore\nGauge" as siloGauge <<Silo>> #$thirdPartyColor {
    asset: wS
}

object "Lending\nMarkets" as siloLend <<Silo>> #$thirdPartyColor {
    markets: stS, wOS, wanS, beS
}
' object "Lending\nMarket\nGauge" as gauge #$thirdPartyColor {
' }
' object "Liquid\nStaking\nToken" as lst #$thirdPartyColor {
' }

object "OS\nVault" as os <<Proxy>> #$originColor {
    asset: wS
}

' object "Beets\nVault" as beets #$thirdPartyColor {
' }

' object "Angles\nVault" as angles #$thirdPartyColor {
' }

object "Origin\nHarvester" as osHarv #$originColor {
    reward: SILO
}

' object "Beets\nHarvester" as stHarv #$originColor {
' }

object "Router" as magpie <<Magpie>> #$thirdPartyColor {
    pair: SILO/wS
}

' object "Price\nProvider" as priceProvider #$originColor {
'     Assets: Silo
' }

' object "Silo\nOracle" as siloOracle #$thirdPartyColor {
' }

' arm .> strat : ERC-4626
' strat .> lend : ERC-4626
' strat ..> gauge
' arm ..> lst

zap ..> originArm
' zap ..> beetsArm
' zap ..> anglesArm

' originArm <..> capMan
' beetsArm <..> capMan
' anglesArm <..> capMan
originArm <.> osCapMan
' beetsArm <.> stCapMan
' anglesArm <..> anCapMan


originArm <... osHarv
' beetsArm <... stHarv

osHarv .> siloStrategy
' stHarv .> siloStrategy

originArm ..> siloStrategy
siloStrategy ..> siloVault
siloStrategy ..> siloGauge
siloVault ..> siloLend
' beetsArm ...> siloStrategy
' anglesArm ..> lend

originArm ..> os
' beetsArm ..> beets
' anglesArm ...> angles

osHarv ..> magpie
' stHarv ..> magpie

' osHarv ..> priceProvider
' stHarv ..> priceProvider
' priceProvider ..> siloOracle


@enduml