@startuml

!$originColor = DeepSkyBlue
' !$originColor = WhiteSmoke
!$newColor = LightGreen
!$changedColor = Orange
!$thirdPartyColor = WhiteSmoke

' legend
' blue - Origin
' white - 3rd Party
' end legend

title "USDC\nAutomated Redemption Manager (ARM)\nContract Dependencies"

object "MultiAssetARM\n(USDC ARM)" as arm <<Origin>><<Proxy>> #$originColor {
    shares: ARM-USDC
    liquidity asset: USDC
    base assets: PYUSD, USDG
}

object "CapManager" as capMan <<Origin>><<Proxy>> #$originColor {
    total-assets cap
    liquidity-provider caps
}

object "PaxosAssetAdapter\n(PYUSD)" as pyusdAdapter <<Origin>><<Proxy>> #$originColor {
    asset: PYUSD
}

object "PaxosAssetAdapter\n(USDG)" as usdgAdapter <<Origin>><<Proxy>> #$originColor {
    asset: USDG
}

object "PYUSD Deposit" as pyusd <<Paxos>> #$thirdPartyColor {
    asset: PYUSD
}

object "USDG Deposit" as usdg <<Paxos>> #$thirdPartyColor {
    asset: USDG
}

capMan <.> arm : deposit caps
arm ..> pyusdAdapter : transfer
arm ..> usdgAdapter : transfer

pyusdAdapter ..> pyusd : transfer

usdgAdapter ..> usdg : transfer

@enduml
